#!/usr/bin/env python3
"""Splice the generated entity tables into hackvertor.sh.

hackvertor.sh is the single-file deliverable.  The two HTML named-reference
tables make it ~35 KB larger, so they are generated by tools/gen_tables.py into
lib/entity_tables.sh and spliced between the two markers below:

    # >>> BEGIN GENERATED ENTITY TABLES (produced by tools/gen_tables.py) >>>
    ...
    # <<< END GENERATED ENTITY TABLES <<<

Run `python3 tools/build.py` after changing the template or the tables.  The
splice is idempotent: running it twice produces the same file.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "hackvertor.sh"
TABLES = ROOT / "lib" / "entity_tables.sh"

BEGIN = "# >>> BEGIN GENERATED ENTITY TABLES (produced by tools/gen_tables.py) >>>"
END = "# <<< END GENERATED ENTITY TABLES <<<"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if the file is stale")
    args = parser.parse_args()

    if not TARGET.exists():
        raise SystemExit(f"{TARGET} not found")
    if not TABLES.exists():
        raise SystemExit(f"{TABLES} not found - run tools/gen_tables.py first")

    text = TARGET.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        raise SystemExit("markers not found in hackvertor.sh")

    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    tables = TABLES.read_text(encoding="utf-8").rstrip("\n")
    rebuilt = f"{head}{BEGIN}\n{tables}\n{END}{tail}"

    if rebuilt == text:
        print("hackvertor.sh is up to date")
        return
    if args.check:
        print("hackvertor.sh is stale - run tools/build.py", file=sys.stderr)
        raise SystemExit(1)

    TARGET.write_text(rebuilt, encoding="utf-8", newline="\n")
    print(f"hackvertor.sh rebuilt ({len(rebuilt)} bytes, +{len(rebuilt) - len(text)})")


if __name__ == "__main__":
    main()
