#!/usr/bin/env python3
"""Generate the HTML named-reference tables used by hackvertor.sh.

Hackvertor's `html_entities` / `html5_entities` tags delegate to the Java
library *unbescape* 1.1.6.RELEASE:

    HtmlEscape.escapeHtml(str, HtmlEscapeType.HTML4_NAMED_REFERENCES_DEFAULT_TO_DECIMAL,
                          HtmlEscapeLevel.LEVEL_3_ALL_NON_ALPHANUMERIC)
    HtmlEscape.escapeHtml(str, HtmlEscapeType.HTML5_NAMED_REFERENCES_DEFAULT_TO_DECIMAL,
                          HtmlEscapeLevel.LEVEL_3_ALL_NON_ALPHANUMERIC)

To be byte-exact, this script does not re-derive the named-reference sets from
the HTML specs: it parses unbescape's own initialisers, which are vendored in
tools/ref/ (copied verbatim from the unbescape sources jar, Apache-2.0):

    Html4EscapeSymbolsInitializer.java   252 references
    Html5EscapeSymbolsInitializer.java  2231 rows (2138 single codepoint)

unbescape's rule (HtmlEscapeSymbols.java, "Only the first NCR for each codepoint
will be used for escaping") is that when several names map to the same codepoint
the FIRST one declared in the initialiser wins, so the tables below are built by
walking the files in order and keeping the first name seen per codepoint.  Two
codepoint sequence entities (`addReference(a, b, "&name;")`) never take part in
escaping and are skipped.

Output: a bash fragment defining two loader functions (see --output).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REF_DIR = Path(__file__).resolve().parent / "ref"

# addReference('x', "&name;")  /  addReference('\u00A0', "&nbsp;")  /  addReference(34, "&quot;")
HTML4_ROW = re.compile(
    r"""addReference\(\s*
        (?P<cp> '(?:\\u[0-9A-Fa-f]{4}|\\.|[^'])' | 0x[0-9A-Fa-f]+ | \d+ )\s*,\s*
        "(?P<name>[^"]*)"\s*\)""",
    re.VERBOSE,
)

# single codepoint HTML5 rows only: the second token must be the name string,
# which excludes the double codepoint form addReference(a, b, "&name;")
HTML5_ROW = re.compile(
    r"""addReference\(\s*
        (?P<cp> 0x[0-9A-Fa-f]+ | \d+ )\s*,\s*
        "(?P<name>[^"]*)"\s*\)""",
    re.VERBOSE,
)

ESCAPES = {"n": "\n", "t": "\t", "r": "\r", "f": "\f", "b": "\b", "0": "\0"}


def parse_char_literal(literal: str) -> int:
    body = literal[1:-1]
    if body.startswith("\\"):
        escape = body[1:]
        if escape.startswith("u"):
            return int(escape[1:], 16)
        if escape in ESCAPES:
            return ord(ESCAPES[escape])
        return ord(escape[0])
    return ord(body)


def parse_codepoint(token: str) -> int:
    token = token.strip()
    if token.startswith("'"):
        return parse_char_literal(token)
    if token.lower().startswith("0x"):
        return int(token, 16)
    return int(token)


def unquote_name(name: str) -> str:
    """'&nbsp;' -> 'nbsp' (names in the initialisers always end with ';')."""
    if name.startswith("&"):
        name = name[1:]
    return name.rstrip(";")


def parse_initializer(path: Path, row_pattern: re.Pattern[str]) -> tuple[dict[int, str], int]:
    """codepoint -> first-declared name, plus the number of rows matched."""
    mapping: dict[int, str] = {}
    rows = 0
    for match in row_pattern.finditer(path.read_text(encoding="utf-8")):
        rows += 1
        codepoint = parse_codepoint(match.group("cp"))
        name = unquote_name(match.group("name"))
        if not name:
            continue
        # first declaration wins, exactly like unbescape
        mapping.setdefault(codepoint, name)
    return mapping, rows


def bash_loader(function_name: str, array_name: str, mapping: dict[int, str]) -> str:
    lines = [f"{function_name}() {{", f"  {array_name}=("]
    for codepoint in sorted(mapping):
        lines.append(f'    [{codepoint}]="{mapping[codepoint]}"')
    lines.append("  )")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default="-", help="write the bash fragment here")
    parser.add_argument("--stats", action="store_true", help="print statistics to stderr")
    args = parser.parse_args()

    html4, rows4 = parse_initializer(REF_DIR / "Html4EscapeSymbolsInitializer.java", HTML4_ROW)
    html5, rows5 = parse_initializer(REF_DIR / "Html5EscapeSymbolsInitializer.java", HTML5_ROW)

    if rows4 != 252:
        raise SystemExit(f"expected 252 HTML4 references, parsed {rows4}")
    if rows5 != 2138:
        raise SystemExit(f"expected 2138 single codepoint HTML5 references, parsed {rows5}")

    fragment = (
        "# --- generated by tools/gen_tables.py from unbescape 1.1.6.RELEASE ---\n"
        "# Do not edit by hand; run: python3 tools/gen_tables.py --output lib/entity_tables.sh\n"
        f"# HTML 4.01 named references: {len(html4)}\n"
        f"{bash_loader('_hv_gen_load_html4', 'HV_HTML4_NAMES', html4)}"
        f"# HTML5 named references (distinct codepoints): {len(html5)}\n"
        f"{bash_loader('_hv_gen_load_html5', 'HV_HTML5_NAMES', html5)}"
    )

    if args.stats:
        print(f"html4 names      : {len(html4)} (rows {rows4})", file=sys.stderr)
        print(f"html5 codepoints : {len(html5)} (single-codepoint rows {rows5})", file=sys.stderr)
        for label, table, probes in (
            ("html4", html4, (34, 39, 45, 47, 61, 92, 126, 233, 8230)),
            ("html5", html5, (9, 34, 39, 45, 47, 61, 92, 94, 124, 126, 233, 256, 8230, 128512)),
        ):
            print(
                f"{label} spot check  : "
                + ", ".join(f"U+{cp:04X}->{table.get(cp, '(numeric)')}" for cp in probes),
                file=sys.stderr,
            )

    if args.output == "-":
        print(fragment, end="")
    else:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(fragment, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
